package com.submodule.branchswitcher

/** Centralized UI strings. Move to Bundle.properties when i18n framework is needed. */
object Strings {
    const val pluginTitle = "Submodule Branch Switcher"
    const val toolWindowId = "SubmoduleBranches"
    const val notificationGroup = "Submodule Branch Switcher"

    const val dirtyStash = "Stash 脏改动"
    const val dirtySkip = "脏则跳过"
    const val dirtyForce = "强制(危险)"
    const val timeoutSeconds = "超时:"
    const val fetchBefore = "切换前 fetch"
    const val pullAfter = "切换后 pull --ff-only"
    const val confirmInit = "init 前确认"

    const val addPreset = "新增预设"
    const val fromCurrent = "从当前状态"
    const val fromCurrentTip = "基于主仓和已 init 子模块的当前 HEAD 分支生成预设"
    const val reloadPresets = "重载预设"
    const val openPresetFile = "打开预设文件"
    const val clearLog = "清空日志"
    const val exportPresets = "导出预设"
    const val importPresets = "导入预设"
    const val undoSwitch = "撤销切换"
    const val undoTip = "撤销最近一次切换，回到切换前的分支状态"

    const val switchToPreset = "切到此预设"
    const val alreadyOnPreset = "已在此预设"
    const val alreadyOnPresetTip = "当前主仓与子模块分支已与该预设一致"
    const val deriveBranch = "派生分支"
    const val deriveTip = "基于此预设创建新分支，主仓+所有子模块同时 checkout -b"
    const val deletePreset = "删除"
    const val save = "保存"
    const val discard = "丢弃"
    const val addSubmodule = "添加子模块"
    const val mainRepo = "主仓"
    const val renameTip = "双击重命名"
    const val switchOnlyThis = "仅切此一仓"
    const val openInExplorer = "在资源管理器打开"

    const val dryRunSwitch = "切换"
    const val dryRunCancel = "取消"
    val dryRunColumns = arrayOf("仓", "当前", "目标", "脏改动", "分支位置")
    const val dryRunClean = "干净"
    const val dryRunLocalOnly = "仅本地"
    const val dryRunRemoteOnly = "仅远端"

    const val switchComplete = "切换完成"
    const val switchFailed = "切换有失败项"
    const val rollbackAction = "回滚到切换前"
    const val rollbackPartial = "回滚部分失败"
    const val rollbackPartialMsg = "部分仓库未能恢复到切换前状态，详见 ToolWindow 日志"
    const val presetLoadFailed = "预设加载失败"
    const val gitRootNotFound = "未找到 git 根目录"
    const val noUndoHistory = "没有可撤销的切换记录"
    const val undoNotFound = "找不到之前的预设"

    const val deleteConfirm = "删除预设"
    const val rename = "重命名"
    const val deriveDialog = "派生功能分支"
    const val fromCurrentDialog = "从当前状态新建预设"
    const val addPresetDialog = "新增预设"
    const val presetNameRule = "预设名（也作为主仓默认分支名,不可与已有预设重名）:"
    const val importDialog = "导入预设"
    const val importEmpty = "剪贴板为空"
    const val importInvalid = "剪贴板内容不是有效的预设 JSON"
    const val importComplete = "导入完成"
    const val exportComplete = "导出完成"
    const val deriveComplete = "派生完成"
    const val undoDialog = "撤销切换"

    const val noPresets = "还没有预设"
    const val noPresetsHint = "预设是一组分支组合，可以一键切换主仓和所有子模块"
    const val fromCurrentCreate = "从当前状态创建"
    const val manualCreate = "手动新增"

    const val mainLabel = "主仓:"

    const val initConfirmTitle = "初始化子模块"
    const val initConfirmMsg = "目录缺失，是否执行 git submodule update --init？"
}
