package com.submodule.branchswitcher.ui

import com.submodule.branchswitcher.Bundle
import com.submodule.branchswitcher.model.DirtyAction

enum class RepoStatusTone {
    NOT_INITIALIZED,
    MATCHED,
    MISMATCHED,
}

data class RepoStatusPresentation(
    val tone: RepoStatusTone,
    val tooltip: String,
)

fun repoStatusPresentation(
    path: String,
    currentBranch: String?,
    targetBranch: String,
    dirty: Boolean,
): RepoStatusPresentation {
    val tone = when {
        currentBranch == null -> RepoStatusTone.NOT_INITIALIZED
        currentBranch == targetBranch -> RepoStatusTone.MATCHED
        else -> RepoStatusTone.MISMATCHED
    }
    val baseTooltip = when (tone) {
        RepoStatusTone.NOT_INITIALIZED -> "$path: ${Bundle.msg("status.tooltip.not.init")}"
        RepoStatusTone.MATCHED -> Bundle.msg("status.tooltip.matched", path, currentBranch!!)
        RepoStatusTone.MISMATCHED -> Bundle.msg("status.tooltip.mismatch", path, currentBranch!!, targetBranch)
    }
    val tooltip = if (dirty) "$baseTooltip · ${Bundle.msg("status.tooltip.dirty")}" else baseTooltip
    return RepoStatusPresentation(tone, tooltip)
}

fun mainStatusText(currentBranch: String, targetBranch: String, dirty: Boolean): String? {
    return when {
        currentBranch != targetBranch -> Bundle.msg("preset.main.diff", currentBranch, targetBranch)
        dirty -> "${Bundle.msg("label.main.repo")} · ${Bundle.msg("status.tooltip.dirty")}"
        else -> null
    }
}

fun strategySummary(dirty: DirtyAction, fetch: Boolean, pull: Boolean, timeoutSeconds: Int): String {
    val dirtyLabel = when (dirty) {
        DirtyAction.Stash -> Bundle.msg("label.strategy.stash")
        DirtyAction.Skip -> Bundle.msg("label.strategy.skip")
        DirtyAction.Force -> Bundle.msg("label.strategy.force")
    }
    val parts = mutableListOf(dirtyLabel)
    if (fetch) parts += Bundle.msg("label.strategy.fetch")
    if (pull) parts += Bundle.msg("label.strategy.pull")
    parts += "${timeoutSeconds}s"
    return parts.joinToString(" · ")
}

/** True when [file] is a Unity `.meta` file (regenerated by Unity on import). */
fun isCollisionFileMeta(file: String): Boolean = file.endsWith(".meta")

/**
 * Summary line for the collision-discard decision. Always reflects "auto" while it is on, so
 * the text is a pure function of the checkbox state — toggling the two options in any order
 * lands on the same summary for the same end state.
 */
fun collisionDiscardSummary(onlyMeta: Boolean, autoMeta: Boolean, metaCount: Int, total: Int): String {
    val approved = if (onlyMeta) metaCount else total
    return when {
        onlyMeta && autoMeta -> Bundle.msg("dialog.collision.discard.summary.meta.auto", approved)
        onlyMeta -> Bundle.msg("dialog.collision.discard.summary.meta", approved)
        autoMeta -> Bundle.msg("dialog.collision.discard.summary.auto", approved, metaCount)
        else -> Bundle.msg("dialog.collision.discard.summary.all", approved)
    }
}

/**
 * Note shown next to one colliding file for the current discard options. Meta files are
 * always discarded — the note only reflects whether they are auto-approved; a non-meta file
 * is kept when only-meta is chosen, which leaves that repo's checkout to fail.
 */
fun collisionFileNote(isMeta: Boolean, onlyMeta: Boolean, autoMeta: Boolean): String = when {
    isMeta && autoMeta -> Bundle.msg("dialog.collision.discard.meta.auto")
    isMeta -> Bundle.msg("dialog.collision.discard.meta.safe")
    onlyMeta -> Bundle.msg("dialog.collision.discard.kept")
    else -> Bundle.msg("dialog.collision.discard.deleted")
}

/** True when the switch must carry a discard confirmation (a non-auto-approved file will be removed). */
fun collisionDiscardNeedsConfirm(files: Iterable<String>, autoMeta: Boolean): Boolean =
    files.any { file -> !(autoMeta && isCollisionFileMeta(file)) }
