package com.submodule.branchswitcher.ui

import com.submodule.branchswitcher.Bundle
import com.submodule.branchswitcher.model.DirtyAction

enum class RepoStatusTone {
    NOT_INITIALIZED,
    MATCHED,
    MISMATCHED,
}

data class RepoStatusPresentation(
    val tone: RepoStatusTone,
    val tooltip: String,
)

fun repoStatusPresentation(
    path: String,
    currentBranch: String?,
    targetBranch: String,
    dirty: Boolean,
): RepoStatusPresentation {
    val tone = when {
        currentBranch == null -> RepoStatusTone.NOT_INITIALIZED
        currentBranch == targetBranch -> RepoStatusTone.MATCHED
        else -> RepoStatusTone.MISMATCHED
    }
    val baseTooltip = when (tone) {
        RepoStatusTone.NOT_INITIALIZED -> "$path: ${Bundle.msg("status.tooltip.not.init")}"
        RepoStatusTone.MATCHED -> Bundle.msg("status.tooltip.matched", path, currentBranch!!)
        RepoStatusTone.MISMATCHED -> Bundle.msg("status.tooltip.mismatch", path, currentBranch!!, targetBranch)
    }
    val tooltip = if (dirty) "$baseTooltip · ${Bundle.msg("status.tooltip.dirty")}" else baseTooltip
    return RepoStatusPresentation(tone, tooltip)
}

fun mainStatusText(currentBranch: String, targetBranch: String, dirty: Boolean): String? {
    return when {
        currentBranch != targetBranch -> Bundle.msg("preset.main.diff", currentBranch, targetBranch)
        dirty -> "${Bundle.msg("label.main.repo")} · ${Bundle.msg("status.tooltip.dirty")}"
        else -> null
    }
}

fun strategySummary(dirty: DirtyAction, fetch: Boolean, pull: Boolean, timeoutSeconds: Int): String {
    val dirtyLabel = when (dirty) {
        DirtyAction.Stash -> Bundle.msg("label.strategy.stash")
        DirtyAction.Skip -> Bundle.msg("label.strategy.skip")
        DirtyAction.Force -> Bundle.msg("label.strategy.force")
    }
    val parts = mutableListOf(dirtyLabel)
    if (fetch) parts += Bundle.msg("label.strategy.fetch")
    if (pull) parts += Bundle.msg("label.strategy.pull")
    parts += "${timeoutSeconds}s"
    return parts.joinToString(" · ")
}

/** True when [file] is a Unity `.meta` file (regenerated by Unity on import). */
fun isCollisionFileMeta(file: String): Boolean = file.endsWith(".meta")

/**
 * Every derived output of the collision-discard decision for one [onlyMeta]/[autoMeta] state.
 * The dialog recomputes a single [CollisionDecision] per checkbox toggle and reads these
 * fields, so the summary, the confirm gate, the counts, and [noteFor] can never disagree
 * about which options were in effect.
 */
data class CollisionDecision(
    val onlyMeta: Boolean,
    val autoMeta: Boolean,
    val summary: String,
    val needsConfirm: Boolean,
    val total: Int,
    val metaCount: Int,
) {
    /** Note shown next to one colliding file under the options this decision was computed for. */
    fun noteFor(file: String): String = when {
        isCollisionFileMeta(file) && autoMeta -> Bundle.msg("dialog.collision.discard.meta.auto")
        isCollisionFileMeta(file) -> Bundle.msg("dialog.collision.discard.meta.safe")
        onlyMeta -> Bundle.msg("dialog.collision.discard.kept")
        else -> Bundle.msg("dialog.collision.discard.deleted")
    }
}

/**
 * Derives all collision-discard outputs from one [onlyMeta]/[autoMeta] state. The summary
 * always reflects "auto" while it is on, so toggling the two options in any order lands on
 * the same decision for the same end state. [collisions] is the full flattened list and the
 * counts are derived from it, so callers cannot pass counts that disagree with the files.
 */
fun collisionDecision(
    collisions: List<String>,
    onlyMeta: Boolean,
    autoMeta: Boolean,
): CollisionDecision {
    val metaCount = collisions.count { isCollisionFileMeta(it) }
    val approved = if (onlyMeta) metaCount else collisions.size
    val summary = when {
        onlyMeta && autoMeta -> Bundle.msg("dialog.collision.discard.summary.meta.auto", approved)
        onlyMeta -> Bundle.msg("dialog.collision.discard.summary.meta", approved)
        autoMeta -> Bundle.msg("dialog.collision.discard.summary.auto", approved, metaCount)
        else -> Bundle.msg("dialog.collision.discard.summary.all", approved)
    }
    return CollisionDecision(
        onlyMeta = onlyMeta,
        autoMeta = autoMeta,
        summary = summary,
        needsConfirm = collisions.any { !(autoMeta && isCollisionFileMeta(it)) },
        total = collisions.size,
        metaCount = metaCount,
    )
}
